### ISSUE TITLE
How to generate the prediction file?

### ISSUE THREAD

**Issue by SkyAndCloud** [Tomiinek/MultiWOZ_Evaluation#1]
Hi, thanks for your great work. I wander how to generate the prediction results file. For example, there is no related scripts in [UBAR code](https://github.com/TonyNemo/UBAR-MultiWOZ), how to generate the predicted results in the expected format?

**Comment by Tomiinek** [comment]
I will try to find the files again later this week, but I really think I do not have it now. Sorry once again

**Comment by SkyAndCloud** [comment]
Got it. BTW, whether did you use the released UBAR checkpoint or train it yourself to generate the predictions? Because lots of people have failed in reproducing UBAR results (even using the released checkpoint). [reference](https://github.com/TonyNemo/UBAR-MultiWOZ/issues/4)

**Comment by Tomiinek** [comment]
Hmm, I see. I used the provided checkpoint which should give [these results](https://github.com/TonyNemo/UBAR-MultiWOZ/issues/3#issuecomment-785850536). But TBH I think that there something messed up in the code base (like leaking ground-truth data during inference, teacher-forcing later predictions etc.), but I was not able to figure out what ... :zipper_mouth_face: It would be great if you were able to find out what is happening there.

 I do not want to be rude, but I should have maybe ignore the model at all in the evaluation. I like [SOLOIST](https://github.com/pengbaolin/soloist) much more.

**Comment by SkyAndCloud** [comment]
I think the reported end-to-end results in UBAR paper is incorrect because they used the golden belief state to generate system actions & responses. We should add an option `use_true_bspn_for_ctr_eval=False` to do end-to-end evaluation in the right way.

**Comment by SkyAndCloud** [comment]
Well, I'm figuring out whether there is something wrong (like teacher-forcing later predictions) in the code base. Have you already find something, or, if you have any suggestions? Maybe I should turn to SOLOIST. lol

**Comment by Tomiinek** [comment]
I think I set `use_true_bspn_for_ctr_eval=False` too, but I still did not trust the results very much :disappointed_relieved:

**Comment by Tomiinek** [comment]
> Well, I'm figuring out whether there is something wrong (like teacher-forcing later predictions) in the code base. Have you already find something, or, if you have any suggestions? Maybe I should turn to SOLOIST. lol

Is there a way to run UBAR in an interactive mode? :thinking:

**Comment by SkyAndCloud** [comment]
I wander whether the inputs of the old-version evaluation are `generated response` and `generated belief states`? `generated system actions` and `generated db` are not included?

**Comment by FatCockHu** [comment]
> Hmm, I see. I used the provided checkpoint which should give [these results](https://github.com/TonyNemo/UBAR-MultiWOZ/issues/3#issuecomment-785850536). But TBH I think that there is something messed up in the code base (like leaking ground-truth data during inference, teacher-forcing later predictions etc.), but I was not able to figure out what ... 🤐 It would be great if you were able to find out what is happening there.
> 
> I do not want to be rude, but I should have maybe ignore the model at all in the evaluation. I like [SOLOIST](https://github.com/pengbaolin/soloist) much more.

I can not find how [SOLOIST](https://github.com/pengbaolin/soloist/issues/2#issue-946054499) generate belief states db. 
Could you give a link ?
