### ISSUE TITLE
ConvLab pipeline approaches

### ISSUE THREAD

**Issue by yukioichida** [Tomiinek/MultiWOZ_Evaluation#7]
Hi,

I am investigating about pipeline task-oriented agents by using the ConvLab-2 toolkit and I have some doubts regarding its results.
I think that their multiwoz evaluation method is not the same, although they use same metrics.
Have you ever evaluate any ConvLab-2 agent by using your scripts? 

Ref: https://github.com/thu-coai/ConvLab-2

**Comment by Tomiinek** [comment]
Hello, 

I am aware of ConvLab, but haven't done any comparisons. However, it is definitely a great idea! 

I do not know how hard it is to make ConvLab working but I might look into it in future days / weeks. Or just in case you have all the things running and working, do not hesitate to share / discuss the results and differences here :slightly_smiling_face: I will be really glad.

Thanks!

**Comment by yukioichida** [comment]
Thanks for your reply.

I am just starting some basic research about evaluation methods in task-oriented systems and, unfortunately, I did not have conclusive results actually. But I intend to share my results.
