### ISSUE TITLE
Is this an error or am I misunderstanding something?

### ISSUE THREAD

**Issue by tomyoung903** [Tomiinek/MultiWOZ_Evaluation#8]
\# Go through the venues returned by the API call matching the dialog state of the current turn and
\# use them as the list of possibly offered venues if and only if any of them is *not* present in the
\# list of possibly offered venues from the previous dialog turn
if current_domain not in offered_venues or len(offered_venues[current_domain]) == 0:
    offered_venues[current_domain] = matching_venues
else:
    if any(venue not in matching_venues for venue in offered_venues[current_domain]): 
        ^ according to the comment above, is this line supposed to be any(venue not in offered_venues[current_domain] for venue in matching_venues)
        offered_venues[current_domain] = matching_venues

**Comment by Tomiinek** [comment]
Hey Tomy :slightly_smiling_face: Thank you for pointing it out! Of course you are absolutely right. The comment is updated in #9 . Feel free to contribute ...

Have a nice day
